version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: docker/go/Dockerfile
    ports: 
      - 8000:8000
    restart: on-failure
    volumes:
      - ./:/go/src/github.com/HETIC-MT-P2021/framework_project
    depends_on:
      - postgres          
    networks:
      - backend
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=db
      - DB_HOST=postgres
      - DB_PORT=5432

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root  
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
      - DATABASE_HOST=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - backend
    restart: unless-stopped

volumes:
  api:
  postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  backend:
    driver: bridge